### ISSUE TITLE
Option to not mute groups by default

### ISSUE THREAD

**Issue by anaskaejdar** [adbenitez/deltalab-android#11]
Hey, adb. We exchanged words about this briefly in the DC Community chat, but I figured I'd put it here in case it helps. I didn't put it in support.delta.chat forum because it appears the forum is for DC broadly, so it would be messy to put something for DL specifically in there.

- Android version: 12
- Device: Samsung GS20
- Delta Chat version: 1.34.2
- Expected behavior: The auto-muting groups change should be optional.
- Actual behavior: There is no setting to change it.
- Steps to reproduce the problem: n/a
- Screenshots: n/a
- Logs: n/a

**Comment by adbenitez** [comment]
hi @anaskaejdar thanks, yes I plan to add an option for this or maybe just don't mute groups anymore and let the users mute them manually

**Comment by adbenitez** [comment]
ok, the changes are already merged, groups will no longer be muted by default in the next version
