### ISSUE TITLE
Can‘t find a way to create backups

### ISSUE THREAD

**Issue by Schweber** [adbenitez/deltalab-android#33]
When creating a new profile, the app offers me the option to restore from backup. However, i can‘t find an option in the app to create a backup.

Maybe i‘m also misunderstanding things but i‘d like to make a backup that contains all my profiles so that i can easily restore them in the future on a new device/new installtion on the same device.

**Comment by adbenitez** [comment]
hi @Schweber :wave: the option to backup your profiles is in the app settings in "Chats and Media", there you can create a backup of the selected profile or all profiles at the same time, this will create a backup file for each profile, importing a backup is done one by one, there is no way to import several backups at the same time at the moment,

if what you want is to add your profile to a second device to use in multi-device, it is much easier to use the "add second device" option that will create the same backup and transmit it over the local network to the new device without you having to copy the backup file around manually

**Comment by adbenitez** [comment]
thanks a lot for your feedback, I agree with you, but if I change it in ArcaneChat, the translation will be wrong for the languages I don't know (I only know English and Spanish) this string comes from the official Delta Chat client, would be nice if it is changed there, maybe open a feature request at https://support.delta.chat

a solution that I think could work is to put a description (text in smaller font that some options have in that screen) in that option

**Comment by r10s** [comment]
i do not think, we "Delta Chat upstream" will change position of "Backup"  soon again.

there were lots of discussions around that all the time (recently [here](https://github.com/deltachat/deltachat-android/issues/2478), it was moved around, some testings say A, some say B. the current position is what WhatsApp and Signal are using. the position is not bad.

it is also worthwhile to have some stability, for both, devs and users, - even if not everyone shares the decisions (never everyone will :)

but i agree that the title/subtitle can be improved (the following dialog is already much more concrete and contains several hints. on desktop/iOS, the button itself is just labelled  "Export Backup" btw)
