### ISSUE TITLE
Blue Theme is the Same as the Grey Theme

### ISSUE THREAD

**Issue by moriel5** [adbenitez/deltalab-android#6]
Upon setting the there in DeltaLab to Blue, I was greeted with a blue-grey color instead, so I continued checking the themes, and all but two behaved as expected, however the Blue and the Grey themes already to be identical.

**Comment by adbenitez** [comment]
could you send screenshots with each of them set? they shouldn't be the same, the blue is blue like Telegram, and the grey theme is grey like the official delta chat color

**Comment by moriel5** [comment]
I'm sorry, this can be marked as invalid.

I may have been half asleep then, with the brightness turned down and blue light filling enabled, however now I can tell the difference.

**Comment by adbenitez** [comment]
haha, thanks for taking care to report anyway :)
